/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.table;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

//TODO:
/*
db/insertData:          ifsAndElses
db/deleteResource:      delete data
get to work bootstrap class path

*/


/**
 *
 * @author Peaq PNB P2015
 */
public class MainPageInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainPageInterface
     */
    public static table hosttable;
    private String[] notificationArray = new String[4];
    
    NewResourceInterface nRI;
    LiveData ld;
    
    public MainPageInterface() {
        initComponents();
        this.setLocation(150, 100);
        
        ld = new LiveData();
        nRI = new NewResourceInterface();
        
        //update model
        RefreshButton.doClick();
        
        //Set E-Mail
        userEmailText.setText(LoginInterface.useremail);
        
        //ToolTips for buttons
        RefreshButton.setToolTipText("Refresh table");
        AddButton.setToolTipText("Add new resource");
        DeleteButton.setToolTipText("Delete resource");
        PlayButton.setToolTipText("Run resource");
        StopButton.setToolTipText("Stop running resources");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RefreshButton = new javax.swing.JButton();
        StopButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resourceTable = new javax.swing.JTable();
        WebButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        NotificationText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        userEmailText = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Resources");

        RefreshButton.setBackground(new java.awt.Color(255, 255, 255));
        RefreshButton.setText("Ref");
        RefreshButton.setBorder(null);
        RefreshButton.setBorderPainted(false);
        RefreshButton.setContentAreaFilled(false);
        RefreshButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        StopButton.setBackground(new java.awt.Color(255, 255, 255));
        StopButton.setText("Stp");
        StopButton.setBorder(null);
        StopButton.setBorderPainted(false);
        StopButton.setContentAreaFilled(false);
        StopButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add");
        AddButton.setBorder(null);
        AddButton.setBorderPainted(false);
        AddButton.setContentAreaFilled(false);
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Del");
        DeleteButton.setBorder(null);
        DeleteButton.setBorderPainted(false);
        DeleteButton.setContentAreaFilled(false);
        DeleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        PlayButton.setBackground(new java.awt.Color(255, 255, 255));
        PlayButton.setText("Pla");
        PlayButton.setBorder(null);
        PlayButton.setBorderPainted(false);
        PlayButton.setContentAreaFilled(false);
        PlayButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        resourceTable.setBackground(new java.awt.Color(240, 240, 240));
        resourceTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        resourceTable.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        resourceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        resourceTable.setFocusable(false);
        resourceTable.setShowHorizontalLines(false);
        resourceTable.setShowVerticalLines(false);
        resourceTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(resourceTable);

        WebButton.setBackground(new java.awt.Color(255, 255, 255));
        WebButton.setBorder(null);
        WebButton.setBorderPainted(false);
        WebButton.setContentAreaFilled(false);
        WebButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        WebButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WebButtonActionPerformed(evt);
            }
        });

        NotificationText.setEditable(false);
        NotificationText.setColumns(1);
        NotificationText.setRows(4);
        NotificationText.setToolTipText("Notification-Box");
        NotificationText.setBorder(null);
        NotificationText.setFocusable(false);
        jScrollPane2.setViewportView(NotificationText);

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("©Tobias Zwinger, Vanessa Lassacher, Semir Beganovic");

        userEmailText.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        userEmailText.setForeground(new java.awt.Color(102, 102, 102));

        LogoutButton.setBackground(new java.awt.Color(255, 255, 255));
        LogoutButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.setToolTipText("Logout");
        LogoutButton.setAlignmentY(0.0F);
        LogoutButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LogoutButton.setContentAreaFilled(false);
        LogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LogoutButton.setMargin(new java.awt.Insets(10, 14, 10, 14));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1223, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddButton)
                        .addGap(2, 2, 2)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(WebButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(userEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WebButton)
                    .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Refresh whole model
    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        //Create resourcetable object
        try {
            hosttable = new table("resources");
        } catch (Exception ex){
            System.err.println("Hosttable not found or no server-connection!");
            System.exit(0);
        }
        
        //Get Model
        DefaultTableModel model = (DefaultTableModel) resourceTable.getModel();
        
        //Delete existing Data
        model.setRowCount(0);
        model.setColumnCount(0);
        
        //Fill resources
        for(String columnName: hosttable.columnNames){
            model.addColumn(columnName);
        }
        model.addColumn("state");
        for(String[] rowName: hosttable.rowNames)
            model.addRow(rowName);
        
        //refresh Notificationbox
        boxUpdate("model updated");
    }//GEN-LAST:event_RefreshButtonActionPerformed
    
// Stop running resources
    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        LiveData.thisIsVisible = false;
        if (ld.isVisible()) ld.setVisible(false);
        for(int i = 0; i < hosttable.rowNames.length; i++){
            String id = (resourceTable.getValueAt(i, 0)).toString();
            try {
                LoginInterface.db.setState(id, false);
            } catch (SQLException ex) {
                Logger.getLogger(LiveData.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        RefreshButtonActionPerformed(evt);
    }//GEN-LAST:event_StopButtonActionPerformed
    // Add new resource
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        if (!nRI.isVisible()){
            boxUpdate("adding resource ...");
            nRI.setVisible(true);
        }else
            boxUpdate("already adding new resource");
    }//GEN-LAST:event_AddButtonActionPerformed
    // Delete selected
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        String id = null;
        int[] selRows = resourceTable.getSelectedRows();
        
        for(int row : selRows){
            id = (resourceTable.getValueAt(row, 0)).toString();
            try {
                LoginInterface.db.deleteResource(id);
            } catch (SQLException ex) {
                Logger.getLogger(MainPageInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        RefreshButtonActionPerformed(evt);
        
        if (selRows.length == 0) boxUpdate("Please select row to delete");
        else if (selRows.length == 1) boxUpdate("resource deleted");
        else if (selRows.length > 1) boxUpdate("resources deleted");
    }//GEN-LAST:event_DeleteButtonActionPerformed
    // Start resource
    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        try {
            LiveData.activeArray = LoginInterface.db.getActiveArray();
        } catch (SQLException ex) {
            Logger.getLogger(LiveData.class.getName()).log(Level.SEVERE, null, ex);
        }
        //LiveDataInterface.running = true;
        
        String id = null;
        int[] selRows = resourceTable.getSelectedRows();
        if (selRows.length == 0){
            boxUpdate("please select row to set resource active");
        }
        else {
            if (!ld.isVisible()) ld.setVisible(true);
            for(int row : selRows){
                id = (resourceTable.getValueAt(row, 0)).toString();
                try {
                    LoginInterface.db.setState(id, true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainPageInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            RefreshButtonActionPerformed(evt);
            boxUpdate("running ...");
        }
        /*
        try {
            //check which are active and create array in Live Data Interface with the active ones
            LiveDataInterface.activeArray = db.getActiveIds();
        } catch (SQLException ex) {
            Logger.getLogger(RessourcenInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }//GEN-LAST:event_PlayButtonActionPerformed
    // Webservice?
    private void WebButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WebButtonActionPerformed
        
    }//GEN-LAST:event_WebButtonActionPerformed
    //Logout
    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        boxUpdate("logout ...");
        
        //close mainInterface
        this.setVisible(false);
        //Open login-Interface
        try {
            new LoginInterface().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainPageInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    //Function to update the notificationbox
    public void boxUpdate(String notification){
        for(int i = 0; i < notificationArray.length-1; i++){
            if (notificationArray[i+1] != null)
                notificationArray[i] = notificationArray[i+1];
            else
                notificationArray[i] = "";
        }
        notificationArray[3] = notification;
        NotificationText.setText(   notificationArray[0] + "\n" + 
                                    notificationArray[1] + "\n" +
                                    notificationArray[2] + "\n" + 
                                    notificationArray[3]);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPageInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPageInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPageInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPageInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPageInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTextArea NotificationText;
    public javax.swing.JButton PlayButton;
    public static javax.swing.JButton RefreshButton;
    public static javax.swing.JButton StopButton;
    private javax.swing.JButton WebButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable resourceTable;
    private javax.swing.JLabel userEmailText;
    // End of variables declaration//GEN-END:variables
}
